trigger:
  branches:
    include:
      - main
      - develop
      - release

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: BuildTestPackage
    displayName: "Build, Test, and Package"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.x"

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: |
          python -m unittest discover
        displayName: "Run unit tests"

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "**/TEST-*.xml"
        displayName: "Publish unit test results"

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          replaceExistingArchive: true
        displayName: "Archive files"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
        displayName: "Publish artifact"

      # Add SonarQube if you have installed
      - task: SonarQubePrepare@4
        inputs:
          SonarQube: "SonarQubeServerConnection"
          scannerMode: "CLI"
          configMode: "manual"
          cliProjectKey: "internal-prod-project"
          cliSources: "."
          extraProperties: |
            sonar.python.coverage.reportPaths=coverage.xml
        displayName: "Prepare analysis on SonarQube"

      - script: |
          sonar-scanner
        displayName: "Run SonarQube analysis"
