version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8080:5000"
    environment:
      DB_PASSWORD: 123456
      DB_PORT: 5432
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: postgres

    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgres_data:
    driver: local
